# Generated by Django 2.2.5 on 2019-10-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0002_auto_20190922_0930'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
